
export const SKILL_CATEGORIES = {
    STRATEGIC: 'skill-strategic',
    EXECUTION: 'skill-execution',
    DATA: 'skill-data',
    DEFAULT: 'skill-default',
};

const STRATEGIC_SKILLS = [
    "Management consulting",
    "Leadership",
    "Strategic Planning & Influence",
    "Go-to-Market (GTM) Strategy",
    "Change Management",
    "Risk Assessment & Governance",
    "Risk Assessment",
    "Risk Governance",
    "Business Acumen",
    "Vendor Lifecycle Management",
    "Contract Management & Governance",
    "Contract Management",
    "Performance Benchmarking",
    "SLA Compliance",
    "Partnership Management",
    "Customer Experience Management",
    "E-commerce Strategy",
    "Performance Marketing",
    "Content Strategy",
    "New Business Development",
    "Partnership Acquisition",
    "Revenue Generation",
    "Client Relationship Management",
    "Revenue Management",
    "Executive Reporting",
    "Financial Management",
    "Billing & Invoicing",
    "Supply & Demand Planning",
    "Team Coordination",
    "Cost Reduction",
    "Operations Management",
    "Market Research",
    "Trend Analysis",
    "Competitive Analysis",
    "Fintech Industry Analysis",
    "Insight Generation",
    "Strategic Reporting",
    "Financial Planning",
    "Investment Strategy",
    "Portfolio Management",
    "Client Advisory",
    "Financial Literacy",
    "Presentation Skills",
    "Workshop Facilitation",
    "Strategic Alignment",
    "Quality Assurance",
    "CSAT Management",
    "Policy Compliance",
    "Stakeholder Communication",
    "Automation",
    "Project Implementation",
    "Stakeholder Management",
    "Performance Tracking",
    "Headcount Planning",
    "Data Visualization",
    "Strategic Communication",
    "Execution Planning",
    "Playbook Development",
    "Data Storytelling",
    "Reporting",
    "Data-Driven Decision Making",
    "Market Research & Analysis",
    "User Experience (UX) Strategy",
    "Marketing Strategy",
    "A/B Testing & Optimization",
    "B2B Operations Management",
    "Revenue & P&L Management",
    "Key Account Management",
    "Partnership Development",
    "Revenue Scaling",
    "Onboarding Process Design",
    "End-to-End SAP Project Lifecycle Management",
    "SAP Technical Solution Design & Architecture",
    "Stakeholder Management & Client Advisory",
    "Service Transition & Operations Management",
    "Google Cloud Platform (GCP) Proficiency",
    "Backend Development",
    "Strategic Planning",
    "Global Communication",
    "Automation Strategy",
    "Product Liaison",
    "Knowledge Management",
    "Client-Specific Analysis",
    "Vendor Management",
    "OPEX Management",
    "Strategic Influence",
    "Go-to-Market Strategy",
    "Macro Definition",
    "Title Optimization",
    "Feed Management",
    "Product Launch Strategy",
];

const EXECUTION_SKILLS = [
    "Program Management",
    "Project Leadership & Execution",
    "Agile Project Management",
    "Stakeholder Management & Communication",
    "Product Management & PRDs",
    "Product Management",
    "Product Requirement Docs",
    "Product Requirement Docs (PRD)",
    "Crisis Management",
    "Business Process Improvement (BPI)",
    "Business Process Improvement",
    "Process Improvement",
    "Process Automation & AI Integration",
    "Process Automation",
    "AI Integration",
    "Operational Excellence & Planning",
    "Operational Excellence",
    "Operational Planning",
    "Scale Management & Scalability",
    "Scale Management",
    "Solution Design & Framework Development",
    "Solution Design",
    "Framework Development",
    "Technical Collaboration",
    "Technical Project Management",
    "Documentation Designing",
    "Program Design & Execution",
    "Cross-Functional Collaboration",
    "Order-to-Cash (O2C) Management",
    "Financial Process Optimization",
    "Logistics & Fulfillment Oversight",
    "Supply Chain Management",
    "Logistics Planning",
    "Process Standardization",
    "Operational Efficiency",
    "System Integration",
    "Solution Implementation & Quality Assurance",
    "Python Programming",
    "Conversational AI Design",
    "API Integration",
    "Project Leadership",
    "Deliverable Management",
    "Time Management & Efficiency",
    "Compliance Management",
    "Project Impact Measurement",
    "Process Scalability",
    "Insight Generation Process Scalability",
    "Project Management",
    "Process Optimization",
    "Escalation Management",
    "Sales Operation"
];

const DATA_SKILLS = [
    "Data-Driven Strategy",
    "Data Storytelling & Visualization",
    "Root Cause Analysis (RCA)",
    "KPI Monitoring & Analysis",
    "Insight Generation & Opportunity Analysis",
    "Opportunity Analysis",
    "Financial Planning & Analysis (FP&A)",
    "Budgeting & OPEX Management",
    "Financial Modeling",
    "Cost-Benefit Analysis & ROI",
    "Cost-Benefit Analysis",
    "Revenue & P&L Management",
    "Client Impact Analysis",
    "Conversion Rate Optimization (CRO)",
    "Data Analysis",
    "Customer Retention Strategy",
    "Invoice Management & Accounts Receivable",
    "Inventory Management",
    "Financial Analysis & Reporting",
    "Quantitative Methods for Investment",
    "Corporate Finance Fundamentals",
    "Asset Valuation (Equity, Fixed Income, Derivatives)",
    "Portfolio Management Principles",
    "Ethical & Professional Standards",
    "Economic Analysis",
    "Analytical Reporting",
    "Budgeting",
    "SQL",
    "Google Ads",
    "Shopping Ads",
    "Dashboards"
];

const skillToClassMap: Record<string, string> = {};

STRATEGIC_SKILLS.forEach(skill => {
    skillToClassMap[skill.toLowerCase()] = SKILL_CATEGORIES.STRATEGIC;
});

EXECUTION_SKILLS.forEach(skill => {
    skillToClassMap[skill.toLowerCase()] = SKILL_CATEGORIES.EXECUTION;
});

DATA_SKILLS.forEach(skill => {
    skillToClassMap[skill.toLowerCase()] = SKILL_CATEGORIES.DATA;
});

export const getSkillClass = (skill: string): string => {
    return skillToClassMap[skill.toLowerCase()] || SKILL_CATEGORIES.DEFAULT;
};

    

    
